config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member do
      get :answer
    end
    resources :comments
  end

  resources :quests
  resource :profile, only: [:show, :edit, :update]

  # API 路徑設定
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :quests, except: [:new, :edit] do
        resources :prompts, shallow: true, only: [:index, :show]
          member do
            post :answer
          end
      end

      resources :posts, except: [:new, :edit] do
        resources :comments, shallow: true, except: [:new, :edit]
        member do
          get "islike", to: "posts#is_like?"
          get "like", to: "posts#user_like"
          get "totallike", to: "posts#total_like"
        end
        member do
          get :user
        end
      end
      resources :ranks do
        collection do
          get :coins
          get :posts
          get :likes
          get :solved
        end
      end
      resources :problems
      resources :coins, only: [:index, :create]
      resources :users, only: [:index, :update] do
        member do
          get :completed_rate
        end
      end
    end
  end

  root to: "pages#index"
  get '/ranking', to: "pages#ranking"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, ImageUploader

  after_create :make_user_profile_default
  after_commit :check_profile_achievement

  def make_user_profile_default
    self.name = user.email.split('@', -1).first
    self.bio = ''
    self.save
  end

  private
  # 檢查成就 - 單項成就 - 個人資料
  def check_profile_achievement
    find_user

    # 更改使用者姓名
    if self.name_before_last_save != nil and self.name_before_last_save != self.name
      badge_id = 18
      create_achievement(badge_id)
    end

    # 大頭貼上傳
    avatar = @user.profile.avatar_url

    if avatar != '/default.png'
      badge_id = 20
      create_achievement(badge_id)
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :current_profile, only: [:show, :edit, :update]

  def show
    @badges = Badge.all
  end

  def edit
  end

  def update
      if @profile.update!(profile_params)
        redirect_to profile_path
      else
        render :edit
      end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :bio, :avatar)
  end

  def current_profile
    @profile = current_user.profile
  end
end

app/views/profiles/edit.html.erb
<section class="user-index-container">
  <div class="profile-edit-wrap">
    <div class="edit-box">
      <%= form_for @profile do |f| %>
        <div class="profile-edit-table">
          <%= f.label :avatar, '上傳圖片' %>
          <%= f.file_field :avatar, accept: 'image/jpg, image/jpeg, image/png, image/gif', class: 'avatar-btn' %>
        </div>
        <div class="profile-edit-table">
          <%= f.label :name, '使用者姓名：' %>
          <%= f.text_field :name, class: 'edit-input'  %>
        </div>
        <div class="profile-edit-table">
          <%= f.label :bio, '簡介：'%>
          <%= f.text_area :bio, id: 'avatar-text', class: 'edit-input edit-text-input', cols: 20, rows: 10 %>
        </div>
        <%= link_to '回上一頁', profile_path, class: 'profile-submitbtn profile-back line-button cursor-pointer' %>
        <%= f.submit "編輯送出", class: 'profile-submitbtn solid-button cursor-pointer' %>
      <% end %>
    </div>
  </div>
</section>

app/views/profiles/show.html.erb
<section class="user-index-container">
  <div class="profile-wrap">
    <div class="profile-user-wrap">
      <p class="profile-table profile-avatar"><%= image_tag(@profile.avatar_url, class: 'avatar') if @profile.avatar_url %></p>
      <p class="profile-table profile-name">使用者名稱：<%= current_user.profile.name %></p>
      <p class="profile-table">簡介：<br/><span class="profile-text markdown-body"><%= current_user.profile.bio %></span></p>
      <%= link_to "編輯", edit_profile_path, class: 'edit-button' %>
    </div>

  <div class="profile-quest-wrap">
    <span class="percentage">題目完成度</span>
    <span class="quest-amount"></span>

    <div class="chart">
      <canvas id="myChart" width="200" height="200"></canvas>
    </div>

    <div class="numerical">
      <div class="easy">
        <span class="title">簡單</span>
        <p></p>
      </div>
      <div class="medium">
        <span class="title">中等</span>
        <p></p>
      </div>
      <div class="hard">
        <span class="title">困難</span>
        <p></p>
      </div>
    </div>

    <div class="allchart">
      <div class="chart">
        <canvas id="easy" width="200" height="200"></canvas>
      </div>
      <div class="chart">
        <canvas id="medium" width="200" height="200"></canvas>
      </div>
      <div class="chart">
        <canvas id="hard" width="200" height="200"></canvas>
      </div>
    </div>
  </div>

  <div class="profile-medal-wrap">
    獎牌區
    <div class="medal-list">
      <% @badges.each do |badge| %>
        <% badge_count = current_user.badges.where(id: badge.id).count %>
        <% if badge_count > 0 %>
          <% is_gotten = 'show' %>
        <% end %>
        <% if badge.id > 20 %>
          <% is_large = 'large' %>
        <% end %>
        <%= image_tag(badge.image, class: "badge #{ is_gotten } #{ is_large }", title: badge.description) %>
      <% end %>
    </div>
  </div>
</section>