config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member do
      get :answer
    end
    resources :comments
  end

  resources :quests
  resource :profile, only: [:show, :edit, :update]

  # API 路徑設定
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :quests, except: [:new, :edit] do
        resources :prompts, shallow: true, only: [:index, :show]
          member do
            post :answer
          end
      end

      resources :posts, except: [:new, :edit] do
        resources :comments, shallow: true, except: [:new, :edit]
        member do
          get "islike", to: "posts#is_like?"
          get "like", to: "posts#user_like"
          get "totallike", to: "posts#total_like"
        end
        member do
          get :user
        end
      end
      resources :ranks do
        collection do
          get :coins
          get :posts
          get :likes
          get :solved
        end
      end
      resources :problems
      resources :coins, only: [:index, :create]
      resources :users, only: [:index, :update] do
        member do
          get :completed_rate
        end
      end
    end
  end

  root to: "pages#index"
  get '/ranking', to: "pages#ranking"
end

app/views/pages/_login.html.erb
<section class="user-index-container">
  <div class="home-box">
    <div class="skill-box">
      <div class="skill-ruby">
        <h2>Ruby 解題進度</h2>
        <div class="progress-bar">
        </div>
        <span class="percent"></span>
        <a href="/quests" class="start-button solid-button">開始測驗</a>
      </div>
    </div>
    <div class="social-box">
      <div class="discuss-box">
        <div class="tag">討論區</div>
        <div class="discuss-list-box">
          <div class="discuss-list first">
          </div>
          <div class="discuss-list second">
          </div>
          <div class="discuss-list third">
          </div>
          <div class="discuss-list fourth">
          </div>
        </div>
      </div>
      <div class="rank-box">
        <div class="tag">排行榜</div>
        <div class="rank-content">
          <div class="rank-button-wrapper">
            <button class="rank-button toggle" data-id="coins">金幣數</button>
            <button class="rank-button" data-id="solved">解題數</button>
            <button class="rank-button" data-id="posts">發文數</button>
            <button class="rank-button" data-id="likes">得讚數</button>
          </div>
          <div class="content-wrapper">
            <div class="content toggle" id="coins">
              <div class="rank-list-box">
                <div class="rank-list coins-1">
                </div>
                <div class="rank-list coins-2">
                </div>
                <div class="rank-list coins-3">
                </div>
              </div>
            </div>
            <div class="content" id="solved">
              <div class="rank-list-box">
                <div class="rank-list solved-1">
                </div>
                <div class="rank-list solved-2">
                </div>
                <div class="rank-list solved-3">
                </div>
              </div>
            </div>
            <div class="content" id="likes">
              <div class="rank-list-box">
                <div class="rank-list likes-1">
                </div>
                <div class="rank-list likes-2">
                </div>
                <div class="rank-list likes-3">
                </div>
              </div>
            </div>
            <div class="content" id="posts">
              <div class="rank-list-box">
                <div class="rank-list posts-1">
                </div>
                <div class="rank-list posts-2">
                </div>
                <div class="rank-list posts-3">
                </div>
              </div>      
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_logout.html.erb
<section class="user-index-container">
  <div class="page-container">
    <div class="img">
      <img src="page.png" alt="">
    </div>
    <div class="title">
      <span>
        <h1>無 限</h1>
        <h1>解 碼 戰</h1>
      </span>
      <%= link_to'註冊 & CODE', new_registration_path(:user), class: 'btn solid-button' %>
    </div>
  </div>
</section>

app/views/pages/index.html.erb
<% if current_user %>
  <%= render "login" %>  
<% else %>
  <%= render "logout" %>    
<% end %>

app/views/pages/ranking.html.erb
<section id="ranking"></section>